# Generated by Django 4.0.3 on 2022-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Published Date')),
                ('title', models.CharField(max_length=40, verbose_name='Announcement Title')),
                ('description', models.TextField(verbose_name='Announcement Description')),
            ],
        ),
    ]
