# Generated by Django 4.0.3 on 2022-03-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('MRP', 'MilitaryRP'), ('DC', 'Discord'), ('WEB', 'Website')], default='MRP', max_length=3),
        ),
    ]
