# Generated by Django 4.0.3 on 2022-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('MilitaryRP', 'MilitaryRP'), ('Discord', 'Discord'), ('Website', 'Website'), ('Community', 'Community')], default='MRP', max_length=12),
        ),
    ]
